### ISSUE TITLE
SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by Helidalto** [Potelo/NfseSsa#1]
Olá, ao tentar utilizar o método "enviarLoteRps" é apresentado a mensagem de erro: SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://notahml.salvador.ba.gov.br/rps/ENVIOLOTERPS/EnvioLoteRPS.svc?wsdl' : failed to load external entity "https://notahml.salvador.ba.gov.br/rps/ENVIOLOTERPS/EnvioLoteRPS.svc?wsdl"

Alguma sugestão?

**Comment by gabrielpeixoto** [comment]
Olá @Helidalto , eu não tinha visto essa Issue.

O erro persistiu?
