### ISSUE TITLE
Dúvida sobre o campo "id" do RPS.

### ISSUE THREAD

**Issue by micaelomota** [Potelo/NfseSsa#11]
Antes de tudo, muito obrigado por publicar essa lib!

A minha dúvida é o que é o campo id usado dentro do `rps` na hora de enviar o lote.

Na doc de exemplo é enviado um campo `id` com o valor `rpsId001` no lote rps:

```php
$result = $nfsa->enviarLoteRps([
          'numero_lote' => 1,
          'id' => '001',
          'cnpj' => '50453974000107',
          'inscricao_municipal' => '51515151515',
          'rps' => [
              'id' => 'rpsId001', // <= esse cara aqui
              'identificacao' => [
                  'numero' => 1,
                  'serie' => 'A',
                  'tipo' => 1 // 1 - RPS, 2 – Nota Fiscal Conjugada (Mista), 3 – Cupom 
              ],
           // ...
```
Vi que ele é passado assim no XML:

https://github.com/Potelo/NfseSsa/blob/master/src/templates/EnviarLoteRPS.blade.php
```php
<LoteRps id="{{ array_get($dados, 'id') }}">
```

E já li a doc do schema em https://notahml.salvador.ba.gov.br/rps/Schema/nfse_salvador.xsd 
mas não não conseguir achar e entender o que significa esse id.

**Comment by gabrielpeixoto** [comment]
Na documentação da prefeitura apenas falam isso:
![image](https://github.com/Potelo/NfseSsa/assets/3699061/c537cabd-1a67-4065-bbcd-8455834c34dc)

Porém funciona normalmente passando os valores fixos que são mostrados no exemplo.
