### ISSUE TITLE
Add Municipios

### ISSUE THREAD

**Issue by danielpinon** [Potelo/NfseSsa#3]
Seu projeto é bom e tem possibilidade de expansão para outros municípios. 
Como Belém: WebService http://siat.nota.belem.pa.gov.br:8180/WsNFe/LoteRps?wsdl

**Comment by gabrielpeixoto** [comment]
Olá @danielpinon muito obrigado!!

Atualmente não estou mexendo nesse projeto, mas se tiver interesse em abrir um Pull Request com suporte a mais municípios, eu revisarei. 😄

**Comment by danielpinon** [comment]
Existe um para php de Nf-e mas não se Nfs-e em php pelo menos revirei a internet e não vi.

**Comment by agnaldofer** [comment]
voce faz o processo de incluir no programa?
