### ISSUE TITLE
Dúvidas na utilização

### ISSUE THREAD

**Issue by deccosantos** [Potelo/NfseSsa#5]
Olá, primeiramente gostaria de parabenizar pelo projeto, mas estou enfrentando dificuldades na utilização dele, basicamente porque nunca trabalhei com o Lavarel.

Eu criei um projeto com o nome app pelo composer usando o comando:
`composer create-project --prefer-dist laravel/laravel app "5.5.*"`

Na sequência baixei o seu projeto usando o comando:
`composer require potelo/nfse-ssa`

Usei o openssl como vc informa para gerar os arquivos .pem do certificado .pfx e usei o comando php artisan vendor:publish --provider="Potelo\NfseSsa\NfseSsaServiceProvider"

Até aí tudo normal, o problema é que eu não sei como criar uma página de teste para tentar emitir a nota fiscal, teria como me ajudar, por favor?

Obrigado

**Comment by gabrielpeixoto** [comment]
Olá!

Você pode criar uma rota e método no arquivo routes/web.php para testar de forma rápida:
```php
Route::get('/', function () {
    return 'Hello World com Laravel';
});
```

**Comment by deccosantos** [comment]
Obrigado pela resposta, mas retornou o erro Uncaught error: Class 'Route' not found in ...
Desculpa incomodar, mas se vc puder me ajudar ficaria muito grato, pois estou tentando ajudar na empresa de meu pai para a implementação de emissão de nota fiscal junto do sistema dele PHP

**Comment by deccosantos** [comment]
@gabrielpeixoto teria como me ajudar, se possível?
