### ISSUE TITLE
Erro E165 - Código de Tributação no Município não está associado ao item da lista serviço indicado no RPS

### ISSUE THREAD

**Issue by vitorpizarro** [Potelo/NfseSsa#6]
Gabriel, parabéns pelo projeto, que estou utilizando para emitir a NF com sucesso usando o CNAE 7490104 e o serviço 1002, porém, agora preciso emitir para o CNAE 6203100 e serviço 00104, porém, quando adiciono estes códigos, recebo a mensagem E165. Os parâmetros que utilizo são:

'servico' => [
                    // TcValores
                    'valores' => [],
                    'item_lista_servico' => "00104", //Testado 104 sem sucesso
                    'codigo_cnae' => 6203100,
                    'discriminacao' => 'Serviço de saúde',
                    'codigo_municipio' => 2927408,
                    'codigo_tributacao_municipio' => '1002009',
                ],

Um erro ocorreu ao criar a nota fiscal. [{"code":"E165","message":"Código de Tributação no Município não está associado ao item da lista serviço indicado no RPS","how_to_fix":"Consulte tabela de código de tributação do município e o item da lista associado no http://nota.salvador.ba.gov.br/artigo_prestador.asp?conteudo=Manuais"}]

Já fiz a consulta sugerida no erro, porém, não consegui identificar o problema.

Grato

**Comment by vitorpizarro** [comment]
Problema identificado. O problema estava no código_tributacao_municipio, ue deveria ser 1002009

**Comment by gabrielpeixoto** [comment]
Olá @vitorpizarro !

Desculpa a demora, fui ver o erro hoje, mas vi que já resolveu! 😁

Qualquer problema pode abrir alguma issue aqui!
