### ISSUE TITLE
dados do tomador

### ISSUE THREAD

**Issue by elinardo10** [Potelo/NfseSsa#7]
Amigo pacote muito legal. estou implementando em cliente de salvador e tenho duvidas a respeito do formato para pessoal fisica, visto q o array só fala de empresa. Tem como vc me ajudar?
'tomador' => [
                  'identificacao_tomador' => [
                      'cpf_cnpj' => [
                          //'cnpj' => '48109110000899',
                          'cpf' => '03537808399' // OU CPF
                      ],
                      //'inscricao_municipal' => '51559500163',
                  ],
                  'razao_social' => 'RAZAO SOCIAL DO CLIENTE S/A',
                  'endereco' => [
                      'endereco' => 'R MANOEL DIAS DA SILVA',
                      'numero' => '1515',
                      'bairro' => 'PITUBA',
                      'codigo_municipio' => 2927408,
                      'uf' => 'BA',
                      'cep' => '41000000',
                  ],
                  'contato' => [
                      'telefone' => '71999999999',
                      'email' => 'email@gmail.com'
                  ]
              ]
              
             tipo como setar o nome? visto q é razão social. alterei para nome, mas tive erro de xml invalido pela sefaz.
             se puder me ajudar

**Comment by gabrielpeixoto** [comment]
Olá @elinardo10 

Eles possuem um xml que descreve todos os campos: https://notahml.salvador.ba.gov.br/rps/Schema/nfse_salvador.xsd

Dá uma olhada aí e vê se consegue entender como é que faz para cpf, nunca fiz na prática para esse cenário!

**Comment by elinardo10** [comment]
erro ao acessar: 403 - Forbidden: Access is denied.
eu colocando como razao_social passa, mas creio q para pessoa fisica n seja o certo, visto q defini um cpf.

**Comment by gabrielpeixoto** [comment]
Olá @elinardo10, para acessar essa página é necessário utilizar o certificado digital que pode ser de algum CPF ou CNPJ.

Vocês já possuem cadastro nesse portal? https://notahml.salvador.ba.gov.br/

Já deu olha olhada no FAQ deles? https://nfse.sefaz.salvador.ba.gov.br/OnLine/Institucional/FaqTecnologia.aspx

**Comment by gabrielpeixoto** [comment]
Ambiente de homologação: https://notahml.salvador.ba.gov.br/

Ambiente de produção: https://nfse.salvador.ba.gov.br/default.aspx
