### ISSUE TITLE
erro E156

### ISSUE THREAD

**Issue by elinardo10** [Potelo/NfseSsa#8]
outro erro que estão encontrando é permissão para emitir nota. meu cliente emite nota normal manual, porem a api retorna dizendo q ele n tem autorização. Sera erro de codigo ou tem q tentar entrar em contato com alguém? onde consigo contato para autorizar essa opção se for o caso, vc saberia informar?
detalhes do erro:
 {
        "codigo": "E156",
        "mensagem": "CNPJ do prestador não autorizado a emitir NFS-e ",
        "correcao": "Solicite autorização para emitir NFS-e para o CNPJ informado."
    }

**Comment by gabrielpeixoto** [comment]
Você consegue suporte a partir dessa página: http://www.nota.salvador.ba.gov.br/fale_conosco_tomador.asp
